//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FazalOil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDetail
    {
        public CustomerDetail()
        {
            this.SaleInvoices = new HashSet<SaleInvoice>();
        }
    
        public long CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<long> CurrentReading { get; set; }
        public Nullable<long> ExpectedChange { get; set; }
        public string DealingEmployee { get; set; }
    
        public virtual ICollection<SaleInvoice> SaleInvoices { get; set; }
    }
}
