//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FazalOil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public long ExpenseID { get; set; }
        public string PersonName { get; set; }
        public string Purpose { get; set; }
        public long Amount { get; set; }
        public System.DateTime Date { get; set; }
    }
}
