//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FazalOil.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class FazilOilEntities : DbContext
    {
        public FazilOilEntities()
            : base("name=FazilOilEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Brand> Brands { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<CustomerDetail> CustomerDetails { get; set; }
        public DbSet<Dropoff> Dropoffs { get; set; }
        public DbSet<Expens> Expenses { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<SaleInvoice> SaleInvoices { get; set; }
        public DbSet<SaleItem> SaleItems { get; set; }
        public DbSet<SaleType> SaleTypes { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<Transaction> Transactions { get; set; }
    
        public virtual ObjectResult<GET_SALES_REPORT_Result> GET_SALES_REPORT(Nullable<long> saleid)
        {
            var saleidParameter = saleid.HasValue ?
                new ObjectParameter("saleid", saleid) :
                new ObjectParameter("saleid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_SALES_REPORT_Result>("GET_SALES_REPORT", saleidParameter);
        }
    
        public virtual ObjectResult<GET_SALES_REPORT_BY_DATE_Result> GET_SALES_REPORT_BY_DATE(string saledateFrom, string saledateTo)
        {
            var saledateFromParameter = saledateFrom != null ?
                new ObjectParameter("saledateFrom", saledateFrom) :
                new ObjectParameter("saledateFrom", typeof(string));
    
            var saledateToParameter = saledateTo != null ?
                new ObjectParameter("saledateTo", saledateTo) :
                new ObjectParameter("saledateTo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_SALES_REPORT_BY_DATE_Result>("GET_SALES_REPORT_BY_DATE", saledateFromParameter, saledateToParameter);
        }
    }
}
