//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FazalOil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long TransactionID { get; set; }
        public long ProductID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public long SupplierID { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<int> TotalCans { get; set; }
        public Nullable<double> CanSize { get; set; }
        public Nullable<double> TotalLitres { get; set; }
        public double PurchasingPrice { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
